// src/lib/navbar/Navbar.svelte
<script lang="ts">
</script>

<div class="navbar-container">
  <div class="title">Monkey<span>recomendation</span></div>
  <div class="made-by">
    Developed by <a href="https://github.com/iguoliveira" target="_blank"
      >{"<iguoliveira />"}</a
    >
  </div>
</div>

<style lang="scss">
  @import "../../variables.scss";
  .navbar-container {
    padding: 20px 20px;
    color: #f4f4f5;
    font-family: Rubik;

    & > .title {
      font-size: 2rem;

      & > span {
        color: $mainColor;
      }
    }

    & > .made-by {
      font-size: 1.25rem;
      & > a {
        text-decoration: none;
        color: $mainColor;
      }
    }
  }
</style>

// frontend/src/components/Navbar.jsx
import "./navbar.scss";
import { Link } from "react-router-dom";

export const Navbar = () => {
  return (
    <nav>
      <div>
        <div className="main-name">
          <Link to="/">
            <span>Monkey</span>
            <span className="project-name">recommendation</span>
          </Link>
        </div>
        <div className="secondary-name">
          <span>Made by:</span>
          <a
            href="https://github.com/iguoliveira"
            target={"_blank"}
            className="name-link"
          >
            {" "}
            iguoliveira
          </a>
        </div>
      </div>
    </nav>
  );
};
